### ISSUE TITLE
Testes unitários do enriquecedor do TCE

### ISSUE THREAD

**Issue by ABuarque** [candidatos-info/enriquecedores#5]
O enriquecimento precisa de testes unitários para garantirmos a qualidade

**Comment by danielfireman** [comment]
Não gosto muito de issues para testes. Acho que testes devem ser parte do código e cada funcionalidade deve pressupor que só estará completa com algum nível de testes.

Acho massa que existam issues para testes específicos ou muito complexos, como por exemplo, alguns testes fim-a-fim. 

Dessa forma, @ABuarque  podemos encerrar essa issue e assumir que as issues das funcionalidades só serão fechadas com algum nível de testes?

**Comment by ABuarque** [comment]
Ciente, encerrando a issue!
