### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by ABuarque** [candidatos-info/enriquecedores#9]
Precisamos de um Dockerfile para podermos facilitar nosso deploy.

**Comment by danielfireman** [comment]
Pode explicar mais sobre isso, @ABuarque ? Perguntando pois, com minha experiência anterior com AppEngine a coisa funciona bem com Go e nem tinha suporte a contêineres docker

**Comment by ABuarque** [comment]
Adicionei antes de ter conhecimento mais prático de app engine, de fato não vi necessidade de uso, vou fechar essa issue
